### ISSUE TITLE
desktop client design

### ISSUE THREAD

**Issue by lachlan-00** [MirakelX/mirakel#20]
do you have any plans for the desktop client completed?
I do a lot of work with python and gtk and would like to help you get a desktop client started.

I would be able to get a linux client for gnome 3 running quickly depending on design. i don't know the current status of gtk3 on windows but if it is still unstable I can write code that would be portable to othe ui toolkits.

**Comment by itadventurer** [comment]
Hey you,
Nowadays we have no plans for a desktop client. But if you want to create one it would be really cool.

## Please write me an email, so we can talk about the next steps: az@azapps.de

Greetings,
Anatolij
