### ISSUE TITLE
Mirakel-dashclock and CM Home

### ISSUE THREAD

**Issue by ghost** [MirakelX/mirakel#24]
When I open and close the CM Home panel (CyanogenMod replacement for Google Now panel which use Dashclock), an error message pop up saying "Mirakel Dashclock has stopped" (translated from French).

I use Mirakel and Mirakel dashclock from Fdroid.

**Comment by itadventurer** [comment]
The current Dashclock version does not work with the old Mirakel version. There are some problems with building Mirakel on F-droid but we are fixing them…

Please just downgrade Mirakel-Dashclock and upgrade it when you get the new Mirakel version

**Comment by ghost** [comment]
Ok, thanks :)
